# Generated by Django 2.2 on 2020-05-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='messages_likes', to='log_reg.User'),
        ),
    ]
